version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: uselagoon/postgres-11
    ports:
      - "5432"
  redis:
    restart: always
    image: uselagoon/redis-5
    ports:
      - "6379"
  elasticsearch:
    image: uselagoon/elasticsearch-7
    restart: always
    ports:
      - "9200"
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - media-root:/code/bakerydemo/media
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
volumes:
  media-root:
